name: CI/CD Pipeline Fashi Template

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Thay vì dùng htmlhint ép chặt lỗi khoảng trắng, ta chỉ cần kiểm tra cơ bản hoặc bỏ qua bước linter nghiêm ngặt để deploy trực tiếp lên Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: '--prod'